title: Amplifire
description: My GitHub Pages site
baseurl: "" # Leave this blank unless your site is in a subfolder
url: "https://amplifire.no"

theme: jekyll-theme-hacker
header_pages:
  - index.md
  - about.md 